-- DEL-30: pin typed modifier snapshot shape.
-- jsonb columns stay; semantic change only — default {} → [] and existing rows backfilled.
-- Code now treats these as Array<ModifierSnapshot>; without backfill, existing {} rows
-- would crash any array-typed reader. Safe to run live: no schema lock, point-in-time UPDATE.

ALTER TABLE "cart_items"
  ALTER COLUMN "modifiers_json" SET DEFAULT '[]'::jsonb;
--> statement-breakpoint
ALTER TABLE "order_line_items"
  ALTER COLUMN "modifiers_snapshot_json" SET DEFAULT '[]'::jsonb;
--> statement-breakpoint

-- Backfill: any pre-existing row with the old {} default becomes []. Hand-added,
-- not generated by drizzle-kit. Idempotent (re-running does nothing).
UPDATE "cart_items"
   SET "modifiers_json" = '[]'::jsonb
 WHERE "modifiers_json" = '{}'::jsonb;
--> statement-breakpoint
UPDATE "order_line_items"
   SET "modifiers_snapshot_json" = '[]'::jsonb
 WHERE "modifiers_snapshot_json" = '{}'::jsonb;
